Repository YAPP-Github/showpot-alarm-backend, pull requests merged in 2024-08, with the labels that each got.

#3 fix : ec2 redis 컨테이너와 네트워크 연동
  docker-compose-alarm-dev.yml
Labels: feat

#6 feat : 구독 정보 알림 sub 구현
  app/api/common-api/build.gradle
  app/api/common-api/src/main/java/org/example/config/PubSubConfig.java
  app/api/common-api/src/main/java/org/example/property/RedisProperty.java
  app/api/subscription-api/build.gradle
  app/api/subscription-api/src/main/java/org/example/config/SubscriptionApiConfig.java
  app/api/subscription-api/src/main/java/org/example/converter/MessageConverter.java
  app/api/subscription-api/src/main/java/org/example/listener/RegisterShowMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/SubscriptionArtistMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/SubscriptionGenreMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/UnsubscriptionArtistMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/UnsubscriptionGenreMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/UpdateShowMessageLister.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/ArtistSubscriptionMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/GenreSubscriptionMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/ShowRelationSubscriptionMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/service/SubscriptionAlarmService.java
  app/api/subscription-api/src/main/java/org/example/service/dto/ArtistSubscriptionMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/GenreSubscriptionMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/SubscriptionMessageServiceRequest.java
  app/domain/common-domain/src/main/resources/application-domain-local.yml
  app/domain/subscription-domain/src/main/java/org/example/dto/ArtistSubscriptionMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/GenreSubscriptionMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/entity/ArtistSubscription.java
  app/domain/subscription-domain/src/main/java/org/example/entity/GenreSubscription.java
  app/domain/subscription-domain/src/main/java/org/example/entity/TicketingAlert.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionQuerydslRepository.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionQuerydslRepositoryImpl.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionRepository.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/genresubscription/GenreSubscriptionQuerydslRepository.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/genresubscription/GenreSubscriptionQuerydslRepositoryImpl.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/genresubscription/GenreSubscriptionRepository.java
  app/domain/subscription-domain/src/main/java/org/example/usecase/ArtistSubscriptionUseCase.java
  app/domain/subscription-domain/src/main/java/org/example/usecase/GenreSubscriptionUseCase.java
  app/infrastructure/build.gradle
  app/infrastructure/fcm/build.gradle
  app/infrastructure/message-queue/build.gradle
  app/infrastructure/src/main/java/org/example/Main.java
  app/src/main/resources/application-local.yml
  settings.gradle
Labels: feat

#8 feat : 티켓팅 알림 예약 구독 구현
  app/api/build.gradle
  app/api/subscription-api/src/main/java/org/example/config/SubscriptionApiConfig.java
  app/api/subscription-api/src/main/java/org/example/converter/SubscriptionMessageConverter.java
  app/api/subscription-api/src/main/java/org/example/listener/RegisterShowMessageListener.java
  app/api/subscription-api/src/main/java/org/example/listener/SubscriptionArtistMessageListener.java
  app/api/subscription-api/src/main/java/org/example/listener/SubscriptionGenreMessageListener.java
  app/api/subscription-api/src/main/java/org/example/listener/UnsubscriptionArtistMessageListener.java
  app/api/subscription-api/src/main/java/org/example/listener/UnsubscriptionGenreMessageListener.java
  app/api/subscription-api/src/main/java/org/example/listener/UpdateShowMessageListener.java
  app/api/ticketing-api/build.gradle
  app/api/ticketing-api/src/main/java/org/example/config/TicketingApiConfig.java
  app/api/ticketing-api/src/main/java/org/example/converter/TicketingMessageConverter.java
  app/api/ticketing-api/src/main/java/org/example/listener/TicketingAlertMessageListener.java
  app/api/ticketing-api/src/main/java/org/example/listener/dto/TicketingReservationMessageApiRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/TicketingAlertService.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/request/TicketingReservationMessageServiceRequest.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/request/TicketingReservationMessageDomainRequest.java
  app/domain/ticketing-domain/src/main/java/org/example/entity/TicketingAlert.java
  app/domain/ticketing-domain/src/main/java/org/example/repository/ticketingalert/TicketingAlertRepository.java
  app/domain/ticketing-domain/src/main/java/org/example/usecase/TicketingAlertUseCase.java
Labels: feat

#10 feat: Spring Quartz를 이용한 알림 설정 스케줄 등록
  app/api/common-api/src/main/java/org/example/error/RedisSubErrorHandler.java
  app/api/subscription-api/src/main/java/org/example/config/SubscriptionApiConfig.java
  app/api/ticketing-api/src/main/java/org/example/batch/TicketingAlertBatch.java
  app/api/ticketing-api/src/main/java/org/example/config/TicketingApiConfig.java
  app/api/ticketing-api/src/main/java/org/example/listener/dto/TicketingReservationMessageApiRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/TicketingAlertService.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/request/TicketingReservationMessageServiceRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/response/TicketingAlertServiceResponse.java
  app/batch/build.gradle
  app/batch/src/main/java/org/example/Main.java
  app/batch/src/main/java/org/example/component/TicketingAlertBatchComponent.java
  app/batch/src/main/java/org/example/config/JobFactoryConfig.java
  app/batch/src/main/java/org/example/config/TicketingAlertJobConfig.java
  app/batch/src/main/java/org/example/job/TicketingAlertQuartzJob.java
  app/batch/src/main/java/org/example/listener/TicketingAlertJobListener.java
  app/batch/src/main/java/org/example/listener/TicketingAlertTriggerListener.java
  app/build.gradle
  app/domain/common-domain/src/main/resources/application-domain-local.yml
  app/domain/ticketing-domain/src/main/java/org/example/dto/request/TicketingAlertTargetDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/request/TicketingReservationMessageDomainRequest.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/response/TicketingAlertDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/response/TicketingAlertToSchedulerDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/repository/ticketingalert/TicketingAlertRepository.java
  app/domain/ticketing-domain/src/main/java/org/example/usecase/TicketingAlertUseCase.java
  app/src/main/java/org/example/ShowPotAlarmApplication.java
Labels: feat

#12 feat: Setting FCM
  .github/workflows/showpotAlarm-dev-cd.yml
  .github/workflows/showpotAlarm-dev-ci.yml
  .gitignore
  app/batch/src/main/java/org/example/service/MessageService.java
  app/batch/src/main/java/org/example/service/dto/request/MultipleTargetsMessageBatchRequest.java
  app/batch/src/main/java/org/example/service/dto/request/SingleTargetMessageBatchRequest.java
  app/domain/subscription-domain/src/main/java/org/example/entity/ArtistSubscription.java
  app/domain/subscription-domain/src/main/java/org/example/entity/GenreSubscription.java
  app/infrastructure/fcm/build.gradle
  app/infrastructure/fcm/src/main/java/org/showpot/client/FCMClient.java
  app/infrastructure/fcm/src/main/java/org/showpot/config/FCMConfig.java
  app/infrastructure/fcm/src/main/java/org/showpot/dto/param/FCMMessageParam.java
  app/infrastructure/fcm/src/main/java/org/showpot/property/FCMProperty.java
  app/infrastructure/fcm/src/main/java/org/showpot/service/FCMMessageService.java
  app/infrastructure/fcm/src/main/resources/application-fcm-dev.yml
  app/infrastructure/fcm/src/main/resources/application-fcm-prod.yml
  app/infrastructure/fcm/src/test/java/org/showpot/FCMInfrastructureTestConfig.java
  app/infrastructure/fcm/src/test/java/org/showpot/client/FCMClientTest.java
  app/infrastructure/fcm/src/test/resources/application.yml
  app/src/main/resources/application-local.yml
  app/src/main/resources/application.yml
  common/src/main/java/org/example/message/MessageParam.java
  common/src/main/java/org/example/message/PushMessageTemplate.java
  config/checkstyle.xml
Labels: feat

#13 fix: Update path of fcm yml
  .github/workflows/showpotAlarm-dev-cd.yml
Labels: fix

#16 fix: 장르, 아티스트 구독 시 FCM 알림, 공연 연관 구독 FCM 알림 연동
  app/api/subscription-api/src/main/java/org/example/SubscriptionMessage.java
  app/api/subscription-api/src/main/java/org/example/converter/SubscriptionMessageConverter.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/ArtistMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/ArtistSubscriptionMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/GenreMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/listener/dto/GenreSubscriptionMessageApiRequest.java
  app/api/subscription-api/src/main/java/org/example/service/SubscriptionAlarmService.java
  app/api/subscription-api/src/main/java/org/example/service/dto/ArtistMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/ArtistSubscriptionMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/GenreMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/GenreSubscriptionMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/MultipleTargetMessageServiceRequest.java
  app/api/subscription-api/src/main/java/org/example/service/dto/SingleTargetMessageServiceRequest.java
  app/api/ticketing-api/src/main/java/org/example/listener/dto/TicketingReservationMessageApiRequest.java
  app/api/ticketing-api/src/main/java/org/example/listener/dto/TicketingTimeMessageApiRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/TicketingAlertService.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/request/TicketingReservationMessageServiceRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/request/TicketingTimeMessageServiceRequest.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/response/TicketingAlertServiceResponse.java
  app/api/ticketing-api/src/main/java/org/example/service/dto/response/TicketingAlertTimeServiceResponse.java
  app/api/ticketing-api/src/main/java/org/example/vo/TicketingAlertTimeApiType.java
  app/batch/src/main/java/org/example/component/TicketingAlertBatchComponent.java
  app/batch/src/main/java/org/example/config/SchedulerJobFactoryConfig.java
  app/batch/src/main/java/org/example/job/TicketingAlertQuartzJob.java
  app/batch/src/main/java/org/example/service/BatchMessage.java
  app/batch/src/main/java/org/example/service/dto/request/SingleTargetMessageBatchRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/request/ArtistMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/request/ArtistSubscriptionMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/request/GenreMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/request/GenreSubscriptionMessageDomainRequest.java
  app/domain/subscription-domain/src/main/java/org/example/dto/response/ArtistSubscriptionDomainResponse.java
  app/domain/subscription-domain/src/main/java/org/example/dto/response/GenreSubscriptionDomainResponse.java
  app/domain/subscription-domain/src/main/java/org/example/entity/ArtistSubscription.java
  app/domain/subscription-domain/src/main/java/org/example/entity/GenreSubscription.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionQuerydslRepository.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/artistsubscription/ArtistSubscriptionQuerydslRepositoryImpl.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/genresubscription/GenreSubscriptionQuerydslRepository.java
  app/domain/subscription-domain/src/main/java/org/example/repository/subscription/genresubscription/GenreSubscriptionQuerydslRepositoryImpl.java
  app/domain/subscription-domain/src/main/java/org/example/usecase/ArtistSubscriptionUseCase.java
  app/domain/subscription-domain/src/main/java/org/example/usecase/GenreSubscriptionUseCase.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/request/TicketingReservationMessageDomainRequest.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/request/TicketingTimeMessageDomainRequest.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/response/TicketingAlertDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/response/TicketingAlertTimeDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/dto/response/TicketingAlertToSchedulerDomainResponse.java
  app/domain/ticketing-domain/src/main/java/org/example/entity/TicketingAlert.java
  app/domain/ticketing-domain/src/main/java/org/example/usecase/TicketingAlertUseCase.java
  app/domain/ticketing-domain/src/main/java/org/example/vo/TicketingAlertTime.java
  app/infrastructure/fcm/build.gradle
  app/infrastructure/fcm/src/main/java/org/showpot/dto/request/MultipleTargetMessageFCMRequest.java
  app/infrastructure/fcm/src/main/java/org/showpot/dto/request/SingleTargetMessageFCMRequest.java
  app/infrastructure/fcm/src/main/java/org/showpot/service/FCMMessageService.java
  app/infrastructure/src/main/java/org/example/config/InfraStructureConfig.java
  app/src/main/java/org/example/ShowPotAlarmApplication.java
  common/src/main/java/org/example/message/PushMessageTemplate.java
Labels: feat, fix

#18 feat: 데모데이용 알림 설정
  app/batch/src/main/java/org/example/component/TicketingAlertBatchComponent.java
  app/infrastructure/fcm/src/test/java/org/showpot/client/FCMClientTest.java
  common/src/main/java/org/example/message/PushMessageTemplate.java
Labels: fix

#20 fix: 로그백 수정
  .github/workflows/showpotAlarm-dev-cd.yml
  app/src/main/resources/application-dev.yml
  app/src/main/resources/logback-spring.xml
Labels: fix
